import type { Metadata } from "next";
import "./globals.css";
import ProviderWrapper from "../redux/ProviderWrapper";

export const metadata: Metadata = {
  title: "Ring of Fire",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.cdnfonts.com/css/i-ice-map"
          rel="stylesheet"
        />
      </head>
      <body>
        <ProviderWrapper>{children}</ProviderWrapper>
      </body>
    </html>
  );
}
